version: "3"
services:

 django_report_builder:
  build:
   context: ./
  volumes:
   - ./django_examples/:/app
   - ./advanced_report_builder/:/app/advanced_report_builder
   - /var/run/docker.sock:/var/run/docker.sock
  command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8010"
  environment:
   - PYTHONPATH=/advanced_report_builder
  ports:
   - 8010:8010
